name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
  COMPILER_CALL:
    description: "The compile to be called on the command line"
    required: true
    default: "gcc"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "box"
  color: "red"
