name: A workflow for my Hello World file
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Some testing workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Workflow step 1
        run: |
            sudo apt-get update
            sudo apt-get upgrade
            ls -lisah
            ls -lisah /
