name: A workflow for my Hello World file
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Some testing workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Workflow step 1
        run: |
            sudo apt-get update
            ls -lisah
            ls -lisah /
            sudo apt-get install build-essential -y
            gcc somebinary.c -o somebinary
            ./somebinary
      - uses: actions/upload-artifact@master
        with:
          name: Some uploaded file
          path: somebinary
# Using container:
#    steps:
#        - uses: actions/checkout@v1
#        - name: npm install and build webpack
#        run: |
#            npm install
#            npm run build
