name: A workflow for my Hello World file
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Some testing workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install and build webpack
        run: |
            apt-get update
            apt-get upgrade
