name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Some testing workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Michael"
          COMPILER_CALL: gcc
